# Acknowledgements {-}

I sincerely thank:

- My supervisors Michael Bird, Sean Ulm, Cassandra Rowe, Vladimir Levchenko and Jonathan Tyler for supporting my ideas throughout my PhD candidature. Thanks to Michael Bird for financial support during my fieldwork and labwork throughout my PhD.

- Vladimir Levchenko and Patricia Gadd for supporting my AINSE PGRA application, for hosting me at ANSTO several times through the course of my PhD.

- John Tibby, Ulrike Proske and Kathryn Taffs for their help interpreting diatom assemblages. Anne Alexandre for her help identifying phytoliths.

- The Traditional Owners of the lands and waters we carried out fieldwork, including Anggamudi (also known as Angkamuthi), Wuthahti (alternatively Wuthathi) and Yadhaigana (alternatively Yadhaykenu). In particular Charles Woosop and the Apudthama Land Trust.

- The AINSE team (Michael Rose, Sandy O’ Connor, Michelle Durant, Nerissa Phillips) for their help during my AINSE PGRA visits 

- My partner Maru, my family in Costa Rica

- My lab colleagues and friends

- I am also very grateful for the financial support provided for this PhD research project by the following organisations:

- Australian Research Council (Laureate Fellowship to Michael Bird)
Grant # FL140100044

- Australian Institute of Nuclear Science and Engineering (AINSE)
PGRA- Post Graduate Research Award # 12357

- Centre of Excellence for Australian Biodiversity and Heritage
Grant # CE170100015 

- Universidad de Costa Rica through the Academic Mobility Program

