# Statement of the Contributions of Others {-}

Standard contributions were made by the supervisory team of Professor Michael Bird, Professor Sean Ulm, Dr. Cassandra Rowe, Dr. Jonathan Tyler and Dr. Vladimir Levchenko. This assistance included project design, technical support, and revisions and editing of this thesis.

```{r st2, echo = FALSE, cache = FALSE, include = FALSE, eval=TRUE, warning=FALSE}


library(knitr)
library(here)
library(bookdown)
library(tidyverse)
library(kableExtra)

st<-read.csv(here("data","statement_contribution_2.csv"))

st2<- st %>%rename('Nature of assistance'= Nature.of.Assistance, 'Names of contributors'= Names..Titles..if.relevant..and.Affiliations.of.Co.Contributors)

#ft_merge <- flextable( st2, cwidth = 2 )
#ft_merge <- merge_v( ft_merge,j = 1 )
#ft_merge

#table100<-regulartable(table5)
#word_export2 <- read_docx()
#body_add_flextable(word_export2, ft_merge)
#body_add_par(word_export2, value = "")

#print(word_export2, target= here("data", "table_contri.docx"))
```

```{r st3, echo = FALSE, cache = FALSE, include = TRUE, eval=TRUE, warning=FALSE}

st2%>%
        knitr::kable("latex", booktabs = T, align = "c",caption="(ref:tb-st2)")%>%
        kableExtra::kable_styling(position = "center")%>% #scale_down
         kableExtra::column_spec(3, width = "5cm")%>%
        collapse_rows(columns = 1, valign = "middle")


```
(ref:tb-st2) Contributions of others to the thesis