# Abstract {-} 

There are no long-term records of climatic and environmental change from Cape York Peninsula in the tropical savannas of northeast Australia. This scarcity has constrained the development and understanding of climate and environmental change in the Australian’s tropics, and thereby the ability to provide context for the long period of human occupation of the region. Lake sediment archives are widely used to recognize changes in climate, precipitation and anthropogenic activities with the potential to significantly extend the length of available observational record by many millennia. Despite the common use of lake sediment proxy indicators to reconstruct climate and environmental histories, existing research demonstrates the complications associated with building robust and accurate chronologies, and interpreting the meaning of observed changes observed from multiple physical, biological and chemical sources of information.

This study was based upon a 1.72 m sediment core from Sanamere Lagoon (11.123°S 142.359°E) with the aim to develop a new record of climate and environmental change for northern Cape York Peninsula. The record spans the last ~33 thousand calibrated years before the present (ka), based on a robust chronology established by comparing age-models derived from multiple carbon fractions (pyrogenic carbon derived from hydrogen pyrolysis -hypy fraction-, macrocharcoal, microcharcoal, pollen concentrate, bulk sediment and cellulose). The age-depth model derived from the hypy fraction was the most reliable and consistent with the stratigraphic changes identified along the core, removing allochthonous carbon and postdepositional contamination. This chronology provided the base for the climatic and environmental reconstructions from the Sanamere sediment core presented in this thesis. 

Time series based on diatoms, phytoliths, hypy fractions, stable isotopes and elemental geochemistry (ITRAX micro X-ray fluorescence scanning) were used to understand the evolution of environmental conditions in the area surrounding Sanamere Lagoon. Four main periods of environmental change were identified (33 - 29.1 ka, 29.1 - 18.2 ka, 18.2 - 9.7 ka and 9.7 ka - present). During the first period, the lagoon formed by collapse of underlying laterite karst terrain, to a level below the local water table, ensuing a continuous record. The lagoon was filled following a wet event, likely related to a southward shift of the Intertropical Convergence Zone (ITCZ) during low sea levels. The results suggest a dominance of dry conditions during the first two identified periods 33 - 18.2 ka. However, no evidence of extreme dry conditions during the Last Glacial Maximum are recorded in the lake sediments. During this time Sanamere Lagoon was a small and shallow water body, with limited organic input. The lagoon expanded and deepened during 18.2 - 9.7 ka, in particular starting at 12.4 ka, following wetter conditions derived from increased monsoon activity and approach of the ocean following sea level rise. The last time period (after 9.7 ka) records increased organic input, related to wet conditions. Between 4.9 - 4.2 ka, high sedimentation rates and changes in the diatom assemblage and geochemical indicators indicate further deepening of the lagoon. Finally, after a slight decrease in rainfall from ~ 4.2 ka, the lagoon stabilised to reach modern conditions. 

Changes in vegetation and fire were recorded using phytoliths and the hypy fractions. The sequence was characterized by the presence of sedges and woody taxa from the beginning to ~ 9.7 ka, with a minimal contribution from grasses. The redevelopment of the monsoon, between 18.2 and 9.7 ka, sustained the dominance of members of Cyperaceae at the site. After 9.7 ka, and particularly after 7.2 ka, wetter conditions sustained a higher proportion of arboreal taxa during the early and middle Holocene, compared to earlier periods. While fire activity is recorded through the entire sequence, activity is increased only during the Holocene. Peaks in the accumulation rates of the hypy fraction at 9.3 and 7.4 - 7.1 ka indicate an increment in fire activity (sustained by a higher availability of biomass to burn) also during the early and middle Holocene. 

The results suggest that sea level was a defining feature of the climate and development of Sanamere Lagoon since its formation. The position of the ITCZ and monsoon activity were also determinant factors in the development of the lagoon. This thesis also brings new insights into the changes in environmental conditions in northern Australia, a region with great potential to understand the interactions between climate, vegetation, fire and humans using a long-term perspective.

This thesis makes a significant contribution to the understanding of environmental change (vegetation, fire and hydrology) in Australia’s monsoonal tropics over the last 33,000 years. It also provides a method for building reliable radiocarbon chronologies in lake sediments, as reliable chronologies are critical for the interpretation of palaeoenvironmental archives in the tropics. Further records of environmental change from tropical Australia, a region that has been continuously inhabited by indigenous Australians for 65,000 years, will enable a more detailed understanding of regional monsoon (palaeo)dynamics and human environment interactions.